#ifndef CONFIG_COMMANDS_H
#define CONFIG_COMMANDS_H

#define CFG_CMD_ENCODE                          "Encode"                    // Video channel property setup (corresponding to CFG_ENCODE_INFO)
#define CFG_CMD_RECORD                          "Record"                    // Schedule record setup
#define CFG_CMD_ALARMINPUT                      "Alarm"                     // External input alarm setup
#define CFG_CMD_NETALARMINPUT                   "NetAlarm"                  // Network alarm setup
#define CFG_CMD_MOTIONDETECT                    "MotionDetect"              // Motion detect alarm setup
#define CFG_CMD_VIDEOLOST                       "LossDetect"                // Video loss alarm setup
#define CFG_CMD_VIDEOBLIND                      "BlindDetect"               // Camera masking alarm setup
#define CFG_CMD_STORAGENOEXIST                  "StorageNotExist"           // No storage device alarm setup
#define CFG_CMD_STORAGEFAILURE                  "StorageFailure"            // The storage device access error alarm setup
#define CFG_CMD_STORAGELOWSAPCE	                "StorageLowSpace"           // The insufficient storage space alarm setup
#define CFG_CMD_NETABORT                        "NetAbort"                  // Network disconnection alarm setup	
#define CFG_CMD_IPCONFLICT                      "IPConflict"                // IP conflict alarm setup
#define CFG_CMD_SNAPCAPINFO                     "SnapInfo"                  // Snapshot competence search
#define CFG_CMD_NAS                             "NAS"                       // NAS setup
#define CFG_CMD_PTZ                             "Ptz"                       // PTZ setup
#define	CFG_CMD_PTZ_AUTO_MOVEMENT               "PtzAutoMovement"           // PTZ Timed Action Configuration(corresponding CFG_PTZ_AUTOMOVE_INFO)
#define CFG_CMD_WATERMARK                       "WaterMark"                 // Video watermark setup
#define CFG_CMD_ANALYSEGLOBAL                   "VideoAnalyseGlobal"        // Video analyze global config(corresponding struct CFG_ANALYSEGLOBAL_INFO)
#define CFG_CMD_ANALYSEMODULE                   "VideoAnalyseModule"        // Video analyze module config(corresponding struct CFG_ANALYSEMODULES_INFO)
#define CFG_CMD_ANALYSERULE                     "VideoAnalyseRule"          // Video analyze rule config(corresponding struct CFG_ANALYSERULES_INFO)
#define CFG_CMD_ANALYSESOURCE                   "VideoAnalyseSource"        // Video analyze source config(corresponding struct CFG_ANALYSESOURCE_INFO)
#define CFG_CMD_RAINBRUSH                       "RainBrush"                 // Rain brush(corresponding struct CFG_RAINBRUSH_INFO)
#define CFG_CMD_INTELLECTIVETRAFFIC             "TrafficSnapshot"           // Intelligent Transport configuration
#define CFG_CMD_TRAFFICGLOBAL                   "TrafficGlobal"             // Traffic global configuration(CFG_TRAFFICGLOBAL_INFO)
#define CFG_CMD_DEV_GENERRAL                    "General"                   // General configuration (corresponding  CFG_DEV_DISPOSITION_INFO)
#define CFG_CMD_ATMMOTION                       "FetchMoneyOverTime"        // ATM motion alarm(struct CFG_ATMMOTION_INFO)
#define CFG_CMD_DEVICESTATUS                    "DeviceStatus"              // Device state information
#define CFG_CMD_HARDDISKTANK                    "HardDiskTank"              // Hard disk tank info
#define CFG_CMD_RAIDGROUP                       "RaidGroup"                 // Raid group information
#define CFG_CMD_STORAGEPOOLGROUP                "StoragePoolGroup"          // Storage pool group information
#define CFG_CMD_STORAGEPOSITIONGROUP            "StoragePositionGroup"      // Storage position group info
#define CFG_CMD_VIDEOINDEVGROUP                 "VideoInDevGroup"           // Video device group information
#define CFG_CMD_DEVRECORDGROUP                  "DevRecordGroup"            // Device record group state
#define CFG_CMD_IPSSERVER                       "IpsServer"                 // Server state
#define CFG_CMD_SNAPSOURCE                      "SnapSource"                // Snap source configuration(struct CFG_SNAPSOURCE_INFO)
#define CFG_CMD_DHRADER                         "DahuaRadar"                // rader configuration (json string only)
#define CFG_CMD_DHRADER_PP                      "DahuaRadar"                // rader configuration (parse to C structure, CFG_DAHUA_RADAR)
#define CFG_CMD_TRANSRADER                      "TransRadar"                // Trans radar configuration
#define CFG_CMD_LANDUNRADER                     "LanDunRadar"               // Landun rader configuration
#define CFG_CMD_LANDUNCOILS                     "LanDunCoils"               // Landun coils configuration
#define CFG_CMD_MATRIX_SPOT                     "SpotMatrix"                // Spot video matrix 
#define CFG_CMD_HDVR_DSP                        "DspEncodeCap"              // DSP encode capability
#define CFG_CMD_HDVR_ATTR_CFG                   "SystemAttr"                // Hdvr's each channel connected device's information
#define CFG_CMD_CHANNEL_HOLIDAY                 "HolidaySchedule"
#define CFG_CMD_HEALTH_MAIL                     "HealthMail"                // Health mail
#define CFG_CMD_CAMERAMOVE                      "IntelliMoveDetect"         // Camera intelligence move detect linkage
#define CFG_CMD_SPLITTOUR                       "SplitTour"                 // Video split tour configuration(Corresponding of CFG_VIDEO_MATRIX) 
#define CFG_CMD_VIDEOENCODEROI                  "VideoEncodeROI"            // Video encode ROI configuration(Region of Interest)
#define CFG_CMD_VIDEO_INMETERING                "VideoInMetering"           // Video inmetering configuration(Corresponding of CFG_VIDEO_INMETERING_INFO) 
#define CFG_CMD_TRAFFIC_FLOWSTAT                "TrafficFlowStat"           // Traffic flow statistic configuration(Corresponding of CFG_TRAFFIC_FLOWSTAT_INFO) 
#define CFG_CMD_HDMIMATRIX                      "HDMIMatrix"                // HDMI matrix configuration
#define CFG_CMD_VIDEOINOPTIONS                  "VideoInOptions"            // Video input front-end option(Corresponding of CFG_VIDEO_IN_OPTIONS)
#define CFG_CMD_RTSP                            "RTSP"                      // RTSP configuration( Corresponding of CFG_RTSP_INFO_IN and CFG_RTSP_INFO_OUT ) 
#define CFG_CMD_TRAFFICSNAPSHOT                 "TrafficSnapshotNew"        // Traffic snapshot(CFG_TRAFFICSNAPSHOT_INFO, discard, use CFG_CMD_TRAFFICSNAPSHOT_MULTI_EX)
#define CFG_CMD_TRAFFICSNAPSHOT_MULTI           "TrafficSnapshotNew"        // Traffic snapshot(CFG_TRAFFICSNAPSHOT_NEW_INFO, discard, use CFG_CMD_TRAFFICSNAPSHOT_MULTI_EX)
#define CFG_CMD_TRAFFICSNAPSHOT_MULTI_EX        "TrafficSnapshotNew"        // Traffic snapshot(CFG_TRAFFICSNAPSHOT_NEW_EX_INFO)
#define CFG_CMD_MULTICAST                       "Multicast"                 // Multicast configuration(Corresponding of CFG_MULTICASTS_INFO_IN and CFG_MULTICASTS_INFO_OUT) 
#define CFG_CMD_VIDEODIAGNOSIS_PROFILE          "VideoDiagnosisProfile"     // Video diagnosis parameter list(CFG_VIDEODIAGNOSIS_PROFILE)
#define CFG_CMD_VIDEODIAGNOSIS_TASK	            "VideoDiagnosisTask"        // Video diagnosis task list (CFG_VIDEODIAGNOSIS_TASK) 
#define CFG_CMD_VIDEODIAGNOSIS_PROJECT          "VideoDiagnosisProject"     // Video diagnosis project(CFG_VIDEODIAGNOSIS_PROJECT) 
#define CFG_CMD_VIDEODIAGNOSIS_REALPROJECT      "VideoDiagnosisRealProject"  // Video Diagnosis Real-time Schedule(CFG_VIDEODIAGNOSIS_REALPROJECT)
#define CFG_CMD_VIDEODIAGNOSIS_GLOBAL           "VideoDiagnosisGlobal"      // Video diagnosis global(CFG_VIDEODIAGNOSIS_GLOBAL) 
#define CFG_CMD_VIDEODIAGNOSIS_TASK_ONE         "VideoDiagnosisTask.x"      // Video diagnosis task list(CFG_VIDEODIAGNOSIS_TASK)  
#define CFG_CMD_TRAFFIC_WORKSTATE               "WorkState"                 // Device workstate Info(Corresponding of CFG_TRAFFIC_WORKSTATE_INFO)
#define CFG_CMD_STORAGEDEVGROUP                 "StorageDevGroup"           // Storage device group configuration(Corresponding of CFG_STORAGEGROUP_INFO)
#define CFG_CMD_RECORDTOGROUP                   "RecordToGroup"             // Video record storage group configuration(Corresponding of CFG_RECORDTOGROUP_INFO) 
#define CFG_CMD_INTELLITRACKSCENE               "IntelliTrackScene"         // Intelligence track scene configuration(CFG_INTELLITRACKSCENE_INFO)
#define CFG_CMD_IVSFRAM_RULE                    "IVSFramRule"               // Intelligence video frame rule(Corresponding of CFG_ANALYSERULES_INFO) 
#define CFG_CMD_RECORD_STORAGEPOINT             "RecordStoragePoint"        // Video record storage point mapping info(Corresponding of CFG_RECORDTOSTORAGEPOINT_INFO) 
#define CFG_CMD_RECORD_STORAGEPOINT_EX			"RecordStoragePoint"		// Video record storage point mapping extend info (Corresponding of CFG_RECORDTOSTORAGEPOINT_EX_INFO)
#define CFG_CMD_MD_SERVER                       "MetaDataServer"	        // Metadata server configuration(Corresponding of CFG_METADATA_SERVER structure body) 
#define CFG_CMD_CHANNELTITLE                    "ChannelTitle"              // Channel name (Corresponding of AV_CFG_ChannelName) 
#define	CFG_CMD_RECORDMODE                      "RecordMode"                // Record mode (Corresponding of AV_CFG_RecordMode) 
#define CFG_CMD_VIDEOOUT                        "VideoOut"                  // Video out property(Corresponding of AV_CFG_VideoOutAttr)
#define CFG_CMD_REMOTEDEVICE                    "RemoteDevice"              // Remote device info (Corresponding of AV_CFG_RemoteDevice array , has no relationship with channel) 
#define CFG_CMD_REMOTECHANNEL                   "RemoteChannel"             // Remote Channel (Corresponding of AV_CFG_RemoteChannel) 
#define CFG_CMD_MONITORTOUR                     "MonitorTour"               // Monitor tour configuration (Corresponding of AV_CFG_MonitorTour) 
#define CFG_CMD_MONITORCOLLECTION               "MonitorCollection"         // Monitor favorite configuration (Corresponding of )
#define CFG_CMD_DISPLAYSOURCE                   "DisplaySource"             // Monitor split display source configuration (Corresponding of AV_CFG_ChannelDisplaySource) 
#define CFG_CMD_RAID                            "Raid"                      // Storage group configuration (Corresponding of AV_CFG_Raid array , has no relationship with channel)
#define CFG_CMD_RECORDSOURCE                    "RecordSource"              // Record source configuration (Corresponding of AV_CFG_RecordSource) 
#define CFG_CMD_VIDEOCOLOR                      "VideoColor"                // Video input color configuration (Corresponding of AV_CFG_ChannelVideoColor)
#define CFG_CMD_VIDEOWIDGET                     "VideoWidget"               // Video widget configuration (Corresponding of AV_CFG_VideoWidget)
#define CFG_CMD_STORAGEGROUP                    "StorageGroup"              // Storage group info. Does not support (Corresponding of AV_CFG_StorageGroup array , has no relationship with channel), 
#define CFG_CMD_LOCALS                          "Locales"                   // Zone configuration (Corresponding of AV_CFG_Locales) 
#define CFG_CMD_LANGUAGE                        "Language"                  // Language (Corresponding of AV_CFG_Language)
#define CFG_CMD_ACCESSFILTER                    "AccessFilter"              // Access filter (Corresponding of AV_CFG_AccessFilter) 
#define CFG_CMD_AUTOMAINTAIN                    "AutoMaintain"              // Automatic maintenance (Corresponding of AV_CFG_AutoMaintain)
#define CFG_CMD_REMOTEEVENT                     "RemoteEvent"               // Remote device event treatment (Corresponding of AV_CFG_RemoteEvent array ) Does not support.
#define CFG_CMD_MONITORWALL                     "MonitorWall"               // Video wall configuration (Corresponding of AV_CFG_MonitorWall array , has no relationship with channel) 
#define	CFG_CMD_SPLICESCREEN                    "VideoOutputComposite"      // Splicing screen configuration (Corresponding of AV_CFG_SpliceScreen array , has no relationship with channel) 
#define CFG_CMD_TEMPERATUREALARM                "TemperatureAlarm"          // Temperature alarm (Corresponding of AV_CFG_TemperatureAlarm, has no relationship with channel) 
#define	CFG_CMD_FANSPEEDALARM                   "FanSpeedAlarm"             // Fan speed alarm (Corresponding of AV_CFG_FanSpeedAlarm, has no relationship with channel)
#define CFG_CMD_RECORDBACKUP                    "RecordBackupRestore"       // Record restore configuration (Corresponding of AV_CFG_RecordBackup, has no relationship with channel)
#define CFG_CMD_RECORDDOWNLOADSPEED		    	"RecordDownloadSpeed"		// Video download speed configuration(corresponding to CFG_RecordDownloadSpeed)
#define CFG_CMD_COMM                            "Comm"                      // COM configuration (Corresponding of CFG_COMMGROUP_INFO)
#define	CFG_CMD_NETWORK                         "Network"                   // Network config (Corresponding of CFG_NETWORK_INFO)
#define CFG_CMD_NASEX                           "NAS"                       // NAS configuration, multi server (Corresponding of CFG_NAS_GROUP_INFO_EX)
#define CFG_CMD_LDAP                            "LDAP"                      // LDAP configuration
#define CFG_CMD_ACTIVE_DIR                      "ActiveDirectory"           // Active directory configuration
#define CFG_CMD_FLASH                           "FlashLight"                // Flash light(Corresponding of CFG_FLASH_LIGHT)
#define CFG_CMD_AUDIO_ANALYSERULE               "AudioAnalyseRule"          // Audio analyse rule(Corresponding of CFG_ANALYSERULES_INFO)
#define CFG_CMD_JUDICATURE                      "Judicature"                // Judicature (Corresponding of CFG_JUDICATURE_INFO)
#define CFG_CMD_GOODS_WEIGHT                    "CQDTSet"                   // CQDT set(Corresponding of CFG_GOOD_WEIGHT_INFO)
#define CFG_CMD_VIDEOIN	                        "VideoIn"                   // VideoIn(Corresponding of CFG_VIDEO_IN_INFO)
#define CFG_CMD_ENCODEPLAN                      "EncodePlan"                // Encode plan(Corresponding of CFG_ENCODE_PLAN_INFO)
#define CFG_CMD_PICINPIC                        "PicInPic"                  // PicInPic(Corresponding of CFG_PICINPIC_INFO)
#define CFG_CMD_BURNFULL                        "BurnFull"                  // Burn full(Corresponding of CFG_BURNFULL_INFO)
#define CFG_CMD_MASTERSLAVE_GLOBAL              "MasterSlaveTrackerGlobal"  // Master slave tracker global(Corresponding of CFG_MASTERSLAVE_GLOBAL_INFO)
#define CFG_CMD_MASTERSLAVE_LINKAGE             "MasterSlaveGlobal"         // Master slave global(Corresponding of CFG_MASTERSLAVE_LINKAGE_INFO)
#define CFG_CMD_MASTERSLAVE_GROUP               "MasterSlaveGroup"          // Master slave group (Corresponding of CFG_MASTERSLAVE_GROUP_INFO)
#define CFG_CMD_ANALYSEWHOLE                    "VideoAnalyseWhole"         // Video analyse whole(Corresponding of CFG_ANALYSEWHOLE_INFO)
#define CFG_CMD_VIDEO_IN_BOUNDARY               "VideoInBoundary"           // Video in boundary(Corresponding of CFG_VIDEO_IN_BOUNDARY)
#define	CFG_CMD_MONITORWALL_COLLECTION          "MonitorWallCollection"	    // Monitor wall collection(Corresponding of CFG_MONITORWALL_COLLECTION array)
#define CFG_CMD_ANALOGMATRIX                    "AnalogMatrix"              // Analog matrix(Corresponding of CFG_ANALOG_MATRIX_INFO)
#define CFG_CMD_ANALOG_MATRIX_PROTOCOL	        "AnalogMatrixProtocol"      // Analog matrix protocol(Corresponding of CFG_ANALOG_MATRIX_PROTOCOL array)
#define	CFG_CMD_VIDEO_OUT_TITLE		            "VideoOutputTitle"          // Video output title(Corresponding of CFG_VIDEO_OUT_TITLE)
#define CFG_CMD_DISK_FLUX_ALARM		            "DiskFluxAlarm"             // Disk flux alarm(Corresponding of CFG_DISK_FLUX_INFO)
#define CFG_CMD_NET_FLUX_ALARM                  "NetFluxAlarm"              // Net flux alarm(Corresponding of CFG_NET_FLUX_INFO)
#define CFG_CMD_DVRIP                           "DVRIP"                     // DVRIP(Corresponding of CFG_DVRIP_INFO)
#define CFG_CMD_PARKINGSPACE_SCREEN             "ParkingSpaceScreen"        // Parking space screen(Corresponding of  CFG_PARKINGSPACE_SCREEN_INFO , is group, element max value is DH_PRODUCTION_DEFNITION.nMaxParkingSpaceScreen)
#define CFG_CMD_PARKINGSPACE_STATUS             "ParkingSpaceCellStatus"    // Parking spaceCell status (Corresponding of  CFG_PARKINGSPACE_STATUS_INFO , is group , element max value is DH_PRODUCTION_DEFNITION.nMaxRoadWays)
#define CFG_CMD_CLIENT_CUSTOM_DATA              "ClientCustomData"          // Client custom data(Corresponding of CFG_CLIENT_CUSTOM_INFO)
#define CFG_CMD_BURN_RECORD_FORMAT              "BurnRecordFormat"          // Burn record format(Corresponding of  CFG_BURN_RECORD_FORMAT)
#define CFG_CMD_MULTIBURN                       "MultiBurn"                 // Multi burn synchronization(Corresponding of CFG_MULTIBURN_INFO)is a group, each group of element means one group multi-disk sync recording and parity
#define	CFG_CMD_ENCODE_ENCRYPT                  "EncodeEncrypt"             // Code Encryption Configuration Information( CFG_ENCODE_ENCRYPT_CHN_INFO )
#define CFG_CMD_VIDEO_IN_ZOOM                   "VideoInZoom"               // Zoom PTZ channel configuration(Corresponding CFG_VIDEO_IN_ZOOM)
#define CFG_CMD_SNAP                            "Snap"                      // Snapshot Configuration (Corresponding CFG_SNAP_INFO)
#define CFG_CMD_REMOTE_STORAGE_LIMIT            "RemoteStorageLimit"        // Network Storage Server Limit Configuration(Corresponding CFG_REMOTE_STORAGELIMIT_GROUP)
#define CFG_CMD_SPECIAL_DIR                     "SpecialDirectoryDefine"    // Special Purpose Directory Definitions(Corresponding CFG_SPECIAL_DIR_INFO)
#define CFG_CMD_AUTO_STARTUP_DELAY              "AutoStartupDelay"          // Delay Automatic Boot  after Shutdown Configuration(Corresponding CFG_AUTO_STARTUP_DELAY_INFO)
#define CFG_CMD_CANFILTER                       "CANFilter"                 // CAN Passthrough Configuration(Corresponding CFG_CANFILTER_LIST)
#define CFG_CMD_VIDEOIN_FOCUS                   "VideoInFocus"              // Focus Setting(Corresponding CFG_VIDEO_IN_FOCUS)
#define CFG_CMD_ENCODE_ADAPT                    "EncodeAdapt"               // Coding Adaptive Configuration(Corresponding CFG_ENCODE_ADAPT_INFO)
#define CFG_CMD_VIDEOANALYSE_CALIBRATE          "VideoAnalyseCalibrate"     // Video Analysis Calibration Configuration(CorrespondingCFG_VIDEO_ANALYSE_CALIBRATEAREA)
#define CFG_CMD_PTZ_PRESET                      "PtzPreset"                 // PTZ Preset Point Configuration(Corresponding structure PTZ_PRESET_INFO)
#define CFG_CMD_TIMESPEEDLIMIT                  "TimeSpeedLimit"            // The Values of Speed Limit Time Configuration(Corresponding structure CFG_TIMESPEEDLIMIT_LIST)
#define CFG_CMD_VOICEALERT                      "VoiceAlert"                // Voice Prompt Configuration(Corresponding structure CFG_VOICEALERT_LIST)
#define CFG_CMD_DEVICEKEEPALIVE	                "DeviceKeepAlive"           // Device Keep Alive Configuration (Corresponding structure CFG_DEVICEKEEPALIVELIST)

#define CFG_CMD_AUDIO_SPIRIT                    "AudioSpirit"               // Voice Incentive(Corresponding CFG_AUDIO_SPIRIT)
#define CFG_CMD_AUDIO_MATRIX_SILENCE    	    "AudioMatrixSilence"   		// Audio matrix silence config (Corresponding CFG_AUDIO_MATRIX_SILENCE)
#define CFG_CMD_AUDIO_MATRIX		            "AudioMatrixConfig"         // Audio matrix config(Corresponding CFG_AUDIO_MATRIX)
#define CFG_CMD_COMPOSE_CHANNEL                 "ComposeChannel"            // Synthetic Channel Configuration(Corresponding CFG_COMPOSE_CHANNEL)
#define CFG_CMD_COMPOSE_LINKAGE                 "ComposeLinkage"            // Synthetic Channel Configuration, Change exhibit (Corresponding CFG_COMPOSE_CHANNEL)
#define CFG_CMD_LOWER_MATRIX                    "LowerMatrix"               // Lower Matrix Configurations(Corresponding CFG_LOWER_MATRIX_LIST) 
#define CFG_CMD_INFRARED_BOARD_TEMPLATE	        "InfraredBoardTemplate"     // Infrared Panel Template(Corresponding CFG_INFRARED_BOARD_TEMPLATE_GROUP)
#define CFG_CMD_INFRARED_BOARD                  "InfraredBoard"             // Infrared Panel Template(Corresponding CFG_INFRARED_BOARD_GROUP)
#define CFG_CMD_VIDEOIN_EXPOSURE                "VideoInExposure"           // Exposure Settings(CorrespondingCFG_VIDEOIN_EXPOSURE_INFO)
#define CFG_CMD_VIDEOIN_BACKLIGHT			    "VideoInBacklight"			// video in back light configuration(Corresponding CFG_VIDEOIN_BACKLIGHT_INFO)

#define CFG_CMD_ACCESS_GENERAL                  "AccessControlGeneral"      // Entrance Guard Basic Configuration(Corresponding CFG_ACCESS_GENERAL_INFO)
#define CFG_CMD_ACCESS_EVENT                    "AccessControl"             // Entrance Guard Event Configuration(Corresponding CFG_ACCESS_EVENT_INFO array)     
#define CFG_CMD_WIRELESS                        "Wireless"                  // Wi-Fi Settings(CorrespondingCFG_WIRELESS_INFO)
#define CFG_CMD_ALARMSERVER                     "AlarmServer"               // Alarm Server Configuration(CorrespondingCFG_ALARMCENTER_INFO)
#define CFG_CMD_COMMGLOBAL                      "CommGlobal"                // Alarm Global Configuration(CorrespondingCFG_COMMALARM_INFO)
#define CFG_CMD_ANALOGALARM	                    "AnalogAlarm"               // Analog Alarm Channel Configuration(CorrespondingCFG_ANALOGALARM_INFO)
#define CFG_CMD_ALARMOUT                        "AlarmOut"                  // Alarm Output Channel Configuration(CorrespondingCFG_ALARMOUT_INFO)
#define CFG_CMD_NTP                             "NTP"                       // Time Synchronization Server(Corresponding CFG_NTP_INFO)
#define CFG_CMD_ALARMBELL                       "AlarmBell"                 // Alarm configuration(CorrespondingCFG_ALARMBELL_INFO)
#define CFG_CMD_MOBILE                          "Mobile"                    // Mobile Related Business Configuration(CorrespondingCFG_MOBILE_INFO)
#define CFG_CMD_PHONEEVENTNOTIFY                "PhoneEventNotify"          // (CorrespondingCFG_PHONEEVENTNOTIFY_INFO)
#define CFG_CMD_PSTN_ALARM_SERVER               "PSTNAlarmServer"           // Telephone Alarm Center Configuration(CFG_PSTN_ALARM_CENTER_INFO)
#define CFG_CMD_AUDIO_OUTPUT_VOLUME	            "AudioOutputVolume"	        // Audio Output Volume(CFG_AUDIO_OUTPUT_VOLUME)
#define CFG_CMD_AUDIO_INPUT_VOLUME              "AudioInputVolume"          // Audio Input Volume(CFG_AUDIO_INPUT_VOLUME)
#define CFG_CMD_LIGHT_GLOBAL					"LightGlobal"				// Indicator light control(CFG_LIGHT_GLOBAL)
#define	CFG_CMD_AUDIO_MIX_VOLUME			    "AudioMixVolume"			// Audio Mix  Volume(CFG_AUDIO_MIX_VOLUME)
#define CFG_CMD_ALARMKEYBOARD                   "AlarmKeyboard"	            // Alarm Keyboard Configuration(CFG_ALARMKEYBOARD_INFO)
#define CFG_CMD_POWERFAULT                      "PowerFault"                // Power Failure Configuration(CFG_POWERFAULT_INFO)
#define CFG_CMD_CHASSISINTRUSION                "ChassisIntrusion"          // Chassis Intrusion Alarm(Tamper Alarm) Configuration(CFG_CHASSISINTRUSION_INFO)
#define CFG_CMD_EXALARMBOX                      "ExAlarmBox"                // Extension Alarm Box Configuration(CFG_EXALARMBOX_INFO)
#define CFG_CMD_EXALARMOUTPUT                   "ExAlarmOut"                // Extension Alarm Output Configuration(CFG_EXALARMOUTPUT_INFO)
#define CFG_CMD_EXALARMINPUT                    "ExAlarm"                   // Extension Alarm Input Configuration(CFG_EXALARMINPUT_INFO)
#define CFG_CMD_ACCESSTIMESCHEDULE              "AccessTimeSchedule"        // Entrance Guard Card Period of Time(CFG_ACCESS_TIMESCHEDULE_INFO)
#define CFG_CMD_URGENCY	                        "Emergency"                 // Emergency Configuration(CFG_URGENCY_INFO)
#define CFG_CMD_SENSORSAMPLING                  "SensorSampling"            // The Sensor Sampling(CFG_SENSORSAMPLING_INFO)
#define CFG_CMD_STP	                            "STP"                       // Ring Network Configuration(CFG_STP_INFO)
#define CFG_CMD_ALARM_SUBSYSTEM	                "AlarmSubSystem"            // Alarm SubConfig(CFG_ALARM_SUBSYSTEM_INFO)
#define CFG_CMD_BATTERY_LOW_POWER               "BatteryLowPowerAlarm"      // Battery Power Min Config(CFG_BATTER_LOW_POWER_INFO)
#define CFG_CMD_SNAPLIKAGE                      "SnapLinkage"               // Snapshot Channel Activation External Config(CFG_SNAPLINKAGE_INFO)
#define CFG_CMD_AUDIOINPUT                      "AudioInput"                // Audio Input Config(CFG_AUDIO_INPUT)
#define CFG_CMD_EMAIL                           "Email"                     // Mail Sending Config(CFG_EMAIL_INFO)
#define CFG_CMD_TRAFFIC_TRANSFER_OFFLINE        "TrafficTransferOffline"    // Send Offline File Config(TRAFFIC_TRANSFER_OFFLINE_INFO)
#define CFG_CMD_COMMSUBSCRIBE		            "CommSubscribe"		        // Order serial data config(CFG_DEVCOMM_SUBSCRIBE)
#define CFG_CMD_PARKINGSPACE_LIGHT_STATE        "ParkingSpaceLightState"    // Vehicle status corresponding spot indicator(CFG_PARKINGSPACE_LIGHT_STATE)
#define CFG_CMD_AIRCONDITION		            "AirCondition"		        // Air conditioner device config(CFG_AIRCONDITION_INFO)
#define CFG_CMD_COMPRESS_PLAY                   "CompressPlay"              // Compression playback config(CFG_COMPRESS_PLAY_INFO)
#define CFG_CMD_BUILDING                        "Building"                  // VTO floor config (CFG_BUILDING_INFO)
#define CFG_CMD_BUILDING_EXTERNAL               "BuildingExternal"          // VTO floor expansion config(CFG_BUILDING_EXTERNAL_INFO)
#define CFG_CMD_DIALRULE                        "DialRule"                  // Dial rule (CFG_DIALRULE_INFO)
#define CFG_CMD_OIL_MASS_INFO                   "OilMassInfo"               // Vehicle tank config(CFG_OIL_MASS_INFO)
#define CFG_CMD_FISHEYE_INFO                    "FishEye"                   // Fish eye detailed info config(CFG_FISHEYE_DETAIL_INFO)
#define CFG_CMD_VTNOANSWER_FORWARD              "VTNoAnswerForward"         // Platform issues call no-response transfer config list(CFG_VT_NOANSWER_FORWARD_INFO)
#define CFG_CMD_VTO_CALL                        "VTOCall"                   // VTO call config (CFG_VTO_CALL_INFO)
#define CFG_CMD_MACCONFLICT                     "MacConflict"               // MAC conflict alarm config(CFG_MACCONFLICT_INFO)
#define CFG_CMD_IDLEMOTION_INFO                 "IdleMotion"                // Idle config(CFG_IDLE_MOTION_INFO)
#define CFG_CMD_MONITORWALL_COLL_TOUR           "MonitorWallCollectionTour" // TV wall scheme tour config(CFG_MONITORWALL_COLLECTION_TOUR_INFO)
#define CFG_CMD_PSTN_BREAK_LINE                 "PSTNBreakLine"             // PSTN offline event config(CFG_PSTN_BREAK_LINE_INFO)
#define CFG_CMD_NET_COLLECTION                  "NetCollection"	            // Network capture device config(CFG_NET_COLLECTION_INFO)
#define CFG_CMD_ALARM_SLOT_BOND                 "AlarmSlotBond"             // Virtual Slot node detailed physical device corresponding relation(CFG_ALARM_SLOT_BOND_INFO)
#define CFG_CMD_TRAFFICSTROBE                   "TrafficStrobe"             // Gateway config(CFG_TRAFFICSTROBE_INFO)
#define CFG_CMD_TRAFFICVOICE                    "TrafficVoiceBroadcast"     // Intelligent traffic audio report config(CFG_TRAFFICVOICE_BROADCAST)
#define CFG_CMD_STANDING_TIME                   "StandingTime"              // Oarking time config(CFG_STANDING_TIME_INFO)
#define CFG_CMD_ENCLOSURE_TIME_SCHEDULE         "EnclosureTimeSchedule"     // E-fence alarm period config(CFG_ENCLOSURE_TIME_SCHEDULE_INFO)
#define CFG_CMD_ECKCONFIG                       "ECKConfig"			        // Parking lot entrance/exit controller config(CFG_ECKCONFIG_INFO)
#define CFG_CMD_PARKING_CARD                    "ParkingCard"               // Parking lot entrance/exit swiping card alarm event config(CFG_PARKING_CARD_INFO)
#define CFG_CMD_RCEMERGENCY_CALL                "RCEmergencyCall"           // Emergency call alarm event config(CFG_RCEMERGENCY_CALL_INFO)
#define CFG_CMD_LANES_STATE_REPORT              "LanesStateReport"          // Lane info report config(CFG_LANES_STATE_REPORT)
#define CFG_CMD_OPEN_DOOR_GROUP                 "OpenDoorGroup"             // Multiple people multi-door combination config(CFG_OPEN_DOOR_GROUP_INFO)
#define CFG_CMD_OPEN_DOOR_ROUTE                 "OpenDoorRoute"             // Unlock path collection, or anti-passby path config(CFG_OPEN_DOOR_ROUTE_INFO)
#define CFG_CMD_BURNPLAN                        "BurnPlan"                  // Burning plan config(corresponding to CFG_BURNPLAN_INFO)
#define CFG_CMD_SCADA_DEV                       "SCADADev"                  // Detect collection device config(CFG_SCADA_DEV_INFO)
#define CFG_CMD_VSP_GAYS                        "VSP_GAYS"                  // Public security 1 platform input config(CFG_VSP_GAYS_INFO)
#define CFG_CMD_AUDIODETECT                     "AudioDetect"               // Audio detection alarm config(CFG_AUDIO_DETECT_INFO group)
#define CFG_CMD_GUIDESCREEN                     "GuideScreen"               // Guide screen config(CFG_GUIDESCREEN_INFO)
#define CFG_CMD_VTS_CALL_INFO                   "VTSCallInfo"               // VTS call config(CFG_VTS_CALL_INFO)
#define CFG_CMD_DEV_LIST                        "DevList"                   // The list of device config(CFG_DEV_LIST_INFO)
#define CFG_CMD_CALIBRATE_MATRIX                "CalibrateMatrix"           // Calibrate matrix config info(CFG_CALIBRATE_MATRIX_INFO)
#define CFG_CMD_DEFENCE_AREA_DELAY              "DefenceAreaDelay"          // Defence area delay config(CFG_DEFENCE_AREA_DELAY_INFO)
#define CFG_CMD_THERMO_GRAPHY                   "ThermographyOptions"       // Thermal imaging camera property config(CFG_THERMOGRAPHY_INFO)
#define CFG_CMD_THERMOMETRY_RULE                "ThermometryRule"           // Thermal imaging Temperature Monitoring rule config(CFG_THERMOMETRY_RULE_INFO)
#define CFG_CMD_TEMP_STATISTICS                 "TemperatureStatistics"     // Temperature statistics config(CFG_TEMP_STATISTICS_INFO)
#define CFG_CMD_THERMOMETRY                     "HeatImagingThermometry"    // Thermal imaging Temperature Monitoring global config(CFG_THERMOMETRY_INFO)
#define CFG_CMD_FLAT_FIELD_CORRECTION           "FlatFieldCorrection"       // Thermal imaging flat field correction config(CFG_FLAT_FIELD_CORRECTION_INFO)
#define CFG_CMD_THERMO_FUSION                   "ThermographyFusion"        // Thermal imaging video fusion config(CFG_THERMO_FUSION_INFO)
#define CFG_CMD_LCE_STATE                       "LCEState"                  // Thermal imaging local contrast enhancement config(CFG_LCE_STATE_INFO)
#define CFG_CMD_LIGHTING                        "Lighting"                  // Configuration of lighting(CFG_LIGHTING_INFO)
#define CFG_CMD_RAINBRUSHMODE                   "RainBrushMode"             // Rain brush mode(CFG_RAINBRUSHMODE_INFO)
#define CFG_CMD_LIGHTINGSCHEDULE                "LightingSchedule"			// Lighting Schedule (CFG_LIGHTINGSCHEDULE_INFO)
#define CFG_CMD_EMERGENCY_RECORD_FOR_PULL       "EmergencyRecordForPull"    // Emergency record for pull when there is someting wrong with pulling(CFG_EMERGENCY_RECORD_FOR_PULL_INFO)
#define CFG_CMD_ALARM_SHIELD_RULE               "AlarmShieldRule"           // Alarm shield rule(CFG_ALARM_SHIELD_RULE_INFO)
#define CFG_CMD_VIDEOIN_ANALYSERULE             "VideoInAnalyseRule"        // Video in analyse rule(CFG_VIDEOIN_ANALYSE_RULE_INFO)
#define CFG_CMD_ACCESS_WORK_MODE                "AccessWorkMode"            // Access work mode(CFG_ACCESS_WORK_MODE_INFO)
#define CFG_CMD_VIDEO_TALK_PHONE_GENERAL        "VideoTalkPhoneGeneral"     // Video talk call general config(CFG_VIDEO_TALK_PHONE_GENERAL)
#define CFG_CMD_TRAFFIC_SNAP_MOSAIC             "TrafficSnapMosaic"         // Snapshot combination config(corresponding to CFG_TRAFFIC_SNAP_MOSAIC_INFO)
#define CFG_CMD_SCENE_SNAP_RULE                 "SceneSnapShotWithRule"     // Scene snapshot setup(corresponding to CFG_SCENE_SNAPSHOT_RULE_INFO)
#define CFG_CMD_PTZTOUR                         "PtzTour"                   // PTZ patrol path config (corresponding to CFG_PTZTOUR_INFO)
#define CFG_CMD_VTO_INFO                        "VTOInfo"                   // VTO config (corresponding to CFG_VTO_LIST)
#define CFG_CMD_TS_POINT                        "TSPoint"                   // Touch screen calibration config (corresponding toCFG_TSPOINT_INFO)
#define CFG_CMD_VTH_NUMBER_INFO                 "VTHNumberInfo"             // VTH no. info (corresponding to CFG_VTH_NUMBER_INFO)
#define CFG_CMD_GPS                             "GPS"                       // GPS config (corresponding to CFG_GPS_INFO_ALL)
#define CFG_CMD_VTO_BASIC_INFO                  "VTOBasicInfo"              // VTO basic info (corresponding to CFG_VTO_BASIC_INFO)
#define CFG_CMD_SHORTCUT_CALL                   "ShortcutCall"              // Quick no. config (corresponding to CFG_SHORTCUT_CALL_INFO)
#define CFG_CMD_GPS_LOCATION_VER                "GPSLocationVersion"        // Record GPSLocation  version no.(corresponding toCFG_LOCATION_VER_INFO)
#define CFG_CMD_PARKING_SPACE_ACCESS_FILTER     "ParkingSpaceAccessFilter"  // Access filter(corresponding to CFG_PARKING_SPACE_ACCESS_FILTER_INFO)
#define CFG_CMD_WORK_TIME                       "WorkTime"                  // work time config(corresponding to CFG_WORK_TIME_INFO)
#define CFG_CMD_PARKING_SPACE_LIGHT_GROUP       "ParkingSpaceLightGroup"    // Parking Space Light Group config(corresponding to CFG_PARKING_SPACE_LIGHT_GROUP_INFO_ALL)
#define CFG_CMD_CUSTOM_AUDIO                    "CustomAudio"               // Custom audio(CFG_CUSTOM_AUDIO)
#define CFG_CMD_WIFI_SEARCH                     "AroudWifiSearch"           // configuration of search wifi device(corresponding to CFG_WIFI_SEARCH_INFO)
#define CFG_CMD_G3G4AUTOCHANGE                  "G3G4AutoChange"            // vehicle-mounted communication module 3G/4G auto change(CFG_G3G4AUTOCHANGE)
#define CFG_CMD_CHECKCODE                       "CheckCode"                 // POS checkcode(corresponding to CFG_CHECKCODE_INFO)
#define CFG_CMD_VSP_SCYDKD                      "VSP_SCYDKD"                // configuration of Sichuan Mobile keep an eye on shop(corresponding to CFG_VSP_SCYDKD_INFO)
#define CFG_CMD_VIDEOIN_DAYNIGHT                "VideoInDayNight"           // day/night color change config (CFG_VIDEOIN_DAYNIGHT_INFO)
#define CFG_CMD_PTZ_POWERUP                     "PowerUp"                   // ptz power up action config ( CFG_PTZ_POWERUP_INFO)
#define CFG_CMD_AUDIO_MIX_CHANNEL               "AudioMixChannel"           // configuration of audio mix channel(corresponding to CFG_AUDIO_MIX_CHANNEL_INFO_ALL)
#define CFG_CMD_AUDIO_TOUCH                     "AudioTouch"                // configuration of audio pitch,change pitch(corresponding to CFG_AUDIO_TOUCH_INFO_ALL)
#define	CFG_CMD_VIDEO_MOSAIC				    "VideoMosaic"				// configuration of video mosaic(corresponding to CFG_VIDEO_MOSAIC_INFO)
#define CFG_CMD_VTH_REMOTE_IPC_INFO             "VTHRemoteIPCInfo"          // configuration of VTH's remote IPC(corresponding to CFG_VTH_REMOTE_IPC_INFO), this config is global, not for single channel 
#define CFG_CMD_UNFOCUSDETECT                   "UnFocusDetect"             // unFocusDetect alarm setup( CFG_UNFOCUSDETECT_INFO)
#define	CFG_CMD_MOVE_DETECT					    "MovedDetect"				// configuration of scene moved detect(corresponding to CFG_MOVE_DETECT_INFO)
#define CFG_CMD_FLOODLIGHT                      "Floodlight"                // configuration of protection flood light(corresponding CFG_FLOODLIGHT_CONTROLMODE_INFO)
#define CFG_CMD_AIRFAN                          "AirFan"                    // configuration of protection airfan(corresponding CFG_AIRFAN_CONTROLMODE_INFO)
#define CFG_CMD_WLAN                            "WLan"                      // configuration of WLAN(corresponding to CFG_NETAPP_WLAN)
#define CFG_CMD_SMART_ENCODE				    "SmartEncode"				// Smart H264 code (corresponding to CFG_SMART_ENCODE_INFO)
#define CFG_CMD_VEHICLE_HIGH_SPEED			    "HighSpeed"					// vehicle mounted high speed alarm config(corresponding to CFG_VEHICLE_HIGHSPEED_INFO )
#define CFG_CMD_VEHICLE_LOW_SPEED			    "LowSpeed"					// vehicle mounted low speed alarm config(corresponding to CFG_VEHICLE_LOWSPEED_INFO )
#define CFG_CMD_PSTN_PERSON_SERVER			    "PSTNPersonServer"			// configuration of answer the personal telephone(corresponding to CFG_PSTN_PERSON_SERVER_INFO_ALL )
#define CFG_CMD_ARM_LINK                	    "ArmLink"			        // configuration of Arm or disarm(corresponding to CFG_ARMLINK_INFO )
#define CFG_CMD_CABINLED_TIME_SCHEDULE          "CabinLedTimeSchedule"      // configuration of time schedule for cabin led(corresponding to CFG_CABINLED_TIME_SCHEDULE)
#define CFG_CMD_PSTN_TESTPLAN                   "PSTNTestPlan"              // configuration of PSTN Test Plan(corresponding to CFG_PSTN_TESTPLAN_INFO)
#define CFG_CMD_DEFENCE_ARMMODE                 "DefenceArmMode"            // configuration of DefenceArm(corresponding to CFG_DEFENCE_ARMMODE_INFO)
#define CFG_CMD_SENSORMODE                      "SensorMode"                // configuration of Sensormode(corresponding to CFG_SENSORMODE_INFO)
#define CFG_CMD_ALARMLAMP                       "AlarmLamp"                 // configuration of AlarmLamp(corresponding to CFG_ALARMLAMP_INFO)
#define CFG_CMD_RADAR_SPEED_MEASURE             "RadarSpeedMeasure"         // configuration of RadarSpeedMeasure(corresponding to CFG_RADAR_SPEED_MEASURE_INFO)
#define CFG_CMD_VIDEOINDEFOG				    "VideoInDefog"				// configuration of defog (corresponding to CFG_VIDEOINDEFOG_LIST)
#define CFG_CMD_RTMP                            "RTMP"                      // configuration of RTMP(corresponding to CFG_RTMP_INFO)
#define CFG_CMD_AUDIO_OUT_EQUALIZER			    "AudioOutEqualizer"			// configuration of  the equalizer of output audio(corresponding to CFG_AUDIO_OUT_EQUALIZER_INFO)
#define CFG_CMD_AUDIO_OUT_SUPPRESSION		    "AudioOutSuppression"		// configuration of the Suppression of output audio channel(corresponding to CFG_AUDIO_OUT_SUPPRESSION_INFO)
#define CFG_CMD_AUDIO_IN_CONTROL			    "AudioInControl"			// configuration of the control of input audio channel (corresponding to CFG_AUDIO_IN_CONTROL_INFO)
#define CFG_CMD_LASER_DIST_MEASURE              "LaserDistMeasure"          // configuration of the distance measure laser (corresponding to CFG_LASER_DIST_MEASURE_INFO)
#define CFG_CMD_OIL_4G_OVERFLOW                 "Oil4GFlow"					// configuration of the fushan oil 4G over flow threshold(corresponding to CFG_OIL_4G_OVERFLOW_INFO)
#define CFG_CMD_OIL_VIDEOWIDGET_4G_FLOW         "VideoWidget4GFlow"			// configuration of the fushan oil 4G flow osd (corresponding to CFG_OIL_VIDEOWIDGET_4G_FLOW_INFO)
#define CFG_CMD_ATMOSPHERE_OSD                  "AtmosphereOSD"             // configuration of the atmosphere osd(corresponding to CFG_CFG_CMD_ATMOSPHERE_OSD_INFO)
#define CFG_CMD_PARK_SPACE_OUT_LIGHT            "ParkSpaceOutLight"         // configuration of light states of the park space(corresponding to CFG_PARK_SPACE_OUT_LIGHT_INFO)
#define CFD_CMD_VTO_CALL_INFO_EXTEND		    "VTOCallInfo"               // extend configuration of VTO call information(corresponding to CFG_VTO_CALL_INFO_EXTEND)
#define CFG_CMD_ACCESS_TEXTDISPLAY              "AccessControlTextDisplay"  // configuration of the access control text display(corresponding to CFG_ACCESS_TEXTDISPLAY_INFO)
#define	CFG_CMD_NETNVR_ENCRYPT				    "NvrEncrypt"				// configuration of the nvr encrypt info(corresponding to CFG_NETNVR_ENCRYPT_INFO )
#define CFG_CMD_LIGHT                           "Light"                     // configuration of the light (corresponding to CFG_LIGHT_INFO)
#define CFG_CMD_CURTAIN                         "Curtain"                   // configuration of the curtain (corresponding to CFG_CURTAIN_INFO)
#define CFG_CMD_FRESH_AIR                       "FreshAir"                  // configuration of the fresh air (corresponding to CFG_FRESH_AIR_INFO)
#define CFG_CMD_GROUND_HEAT                     "GroundHeat"                // configuration of the ground heat (corresponding to CFG_GROUND_HEAT_INFO)
#define CFG_CMD_SCENE_MODE                      "SceneMode"                 // configuration of the scene mode (corresponding to CFG_SCENE_MODE_INFO)
#define CFG_CMD_AIO_APP_CONFIG				    "AIOAppConfig"				// configuration of the AOIAppConfig (corresponding to CFG_AIO_APP_CONFIG_INFO)
#define CFG_CMD_HTTPS                           "Https"                     // configuration of https server (corresponding to CFG_HTTPS_INFO)
#define CFG_CMD_NETAUTOADAPTORENCODE            "NetAutoAdaptEncode"        // configuration of net auto adapt(corresponding to CFG_NET_AUTO_ADAPT_ENCODE)
#define CFG_CMD_USERLOCKALARM				    "UserLockAlarm"				// login lock config(CFG_USERLOCKALARM_INFO)
#define CFG_CMD_STROBOSCOPIC_LAMP               "StroboscopicLamp"          // configuration of the Stroboscopic lamp(corresponding to CFG_STROBOSCOPIC_LAMP_INFO)
#define CFG_CMD_FREECOMBINATION                 "FreeCombination"           // configuration of the free combination(corresponding to CFG_FREECOMBINATION_INFO )
#define CFG_CMD_IOT_INFRARED_DETECT			    "IOT_InfraredDetect"		// configuration of IOT infrared  detection(corresponding to CFG_IOT_INFRARED_DETECT_INFO)
#define CFG_CMD_IOT_RECORD_HANDLE			    "IOT_RecordHandle"			// configuration of IOT record handle(corresponding to CFG_IOT_RECORD_HANDLE_INFO)
#define CFG_CMD_IOT_SNAP_HANDLE				    "IOT_SnapHandle"			// configuration of IOT snap handle(corresponding to CFG_IOT_SNAP_HANDLE_INFO)
#define CFG_CMD_PLATFORM_MONITOR_IPC            "PlatformMonitorIPC"        // configuration of the platform monitor ipc(corresponding to CFG_PLATFORMMONITORIPC_INFO )
#define CFG_CMD_CALLFORWARD                     "CallForward"               // configuration of the call forward(corresponding to CFG_CALLFORWARD_INFO)
#define CFD_CMD_DOORBELLSOUND                   "DoorBellSound"             // configuration of door bell sound(corresponding to CFG_DOOR_BELLSOUND_INFO)
#define CFG_CMD_TELNET                          "Telnet"                    // configuration of Telnet(corresponding to CFG_TELNET_INFO)
#define CFG_CMD_OSDSYSABNORMAL				    "OSDSysAbnormal"			// configuration of abnormal information OSD(corresponding to CFG_OSD_SYSABNORMAL_INFO)
#define CFG_CMD_VIDEO_WIDGET2				    "VideoWidget2"				// configuration of video encode staff(corresponding to CFG_VIDEO_WIDGET2_INFO)
#define CFG_CMD_VIDEOWIDGET_NUMBERSTAT		    "VideoWidgetNumberStat"		// configuration of number count OSD(corresponding to CFG_VIDEOWIDGET_NUMBERSTAT_INFO)
#define CFG_CMD_PRIVACY_MASKING				    "PrivacyMasking"			// configuration of privacy masking(corresponding to CFG_PRIVACY_MASKING_INFO)
#define CFG_CMD_DEVICE_INFO					    "DeviceInfo"				// configuration of device infomation(corresponding to CFG_DEVICE_INFO)
#define CFG_CMD_POLICEID_MAP_INFO			    "PoliceMap"				    // configuration of police id map info(corresponding to CFG_POLICEID_MAP_INFO)
#define CFG_CMD_GPS_NOT_ALIGNED                 "GpsNotAligned"             // configuration of Gps not aligned(corresponding to CFG_GPS_NOT_ALIGNED_INFO) 
#define CFG_CMD_WIRELESS_NOT_CONNECTED          "WireLessNotConnected"      // configuration of WireLess not connected(corresponding to CFG_WIRELESS_NOT_CONNECTED_INFO)
#define CFG_CMD_MCS_GENERAL_CAPACITY_LOW		"MCSGeneralCapacityLow"		// configuration of MCS general capacity low(corresponding to CFG_MCS_GENERAL_CAPACITY_LOW)
#define CFG_CMD_MCS_DATA_NODE_OFFLINE			"MCSDataNodeOffline"		// configuration of MCS data node offline(corresponding to CFG_MCS_DATA_NODE_OFFLINE)
#define CFG_CMD_MCS_DISK_OFFLINE				"MCSDiskOffline"			// configuration of MCS disk offline(corresponding to CFG_MCS_DISK_OFFLINE)
#define CFG_CMD_MCS_DISK_SLOW					"MCSDiskSlow"				// configuration of MCS disk slow(corresponding to CFG_MCS_DISK_SLOW)
#define CFG_CMD_MCS_DISK_BROKEN					"MCSDiskBroken"				// configuration of MCS disk broken(corresponding to CFG_MCS_DISK_BROKEN)
#define CFG_CMD_MCS_DISK_UNKNOW_ERROR			"MCSDiskUnknowError"		// configuration of MCS disk unknow error(corresponding to CFG_MCS_DISK_UNKNOW_ERROR)
#define CFG_CMD_MCS_METADATA_SERVER_ABNORMAL	"MCSMetadataServerAbnormal" // configuration of MCS metadata server abnormal(corresponding to CFG_MCS_METADATA_SERVER_ABNORMAL)
#define CFG_CMD_MCS_CATALOG_SERVER_ABNORMAL		"MCSCatalogServerAbnormal"	// configuration of MCS catalog server abnormal(corresponding to CFG_MCS_CATALOG_SERVER_ABNORMAL)
#define CFG_CMD_MCS_GENERAL_CAPACITY_RESUME		"MCSGeneralCapacityResume"	// configuration of MCS general capacity resume(corresponding to CFG_MCS_GENERAL_CAPACITY_RESUME)
#define CFG_CMD_MCS_DATA_NODE_ONLINE			"MCSDataNodeOnline"			// configuration of MCS data node online(corresponding to CFG_MCS_DATA_NODE_ONLINE)
#define CFG_CMD_MCS_DISK_ONLINE					"MCSDiskOnline"				// configuration of MCS disk online(corresponding to CFG_MCS_DISK_ONLINE)
#define CFG_CMD_MCS_METADATA_SLAVE_ONLINE		"MCSMetadataSlaveOnline"	// configuration of MCS metadata slave online(corresponding to CFG_MCS_METADATA_SLAVE_ONLINE)
#define CFG_CMD_MCS_CATALOG_SERVER_ONLINE		"MCSCatalogServerOnline"	// configuration of MCS catalog server online(corresponding to CFG_MCS_CATALOG_SERVER_ONLINE)
#define CFG_CMD_SECURITY_ALARMS_PRIVACY         "SecurityAlarmsPrivacy"     // configuration of Privacy protection (corresponding to CFG_SECURITY_ALARMS_PRIVACY)
#define CFG_CMD_NO_FLY_TIME                     "NoFlyTime"                 // configuration of no fly time ( corresponding to CFG_NO_FLY_TIME_INFO )
#define CFG_CMD_PWD_RESET                       "PwdReset"                  // configuration of pwd reset enable ( corresponding to CFG_PWD_RESET_INFO )
#define	CFG_CMD_NET_MONITOR_ABORT				"NetMonitorAbort"			// configuration of Net Monitor Abort ( corresponding to CFG_NET_MONITOR_ABORT_INFO )
#define CFG_CMD_LOCAL_EXT_ALARM                 "LocalExtAlarm"             // configuration of Local Ext Alarm ( corresponding to CFG_LOCAL_EXT_ALARME_INFO )
#define CFG_CMD_ACCESSCONTROL_DELAYSTRATEGY     "DelayStrategy"             // configuration of AccessControl card Delay strategy(corresponding to CFG_ACCESSCONTROL_DELAYSTRATEGY)
#define	CFG_CMD_VIDEO_TALK_PHONE_BASIC			"VideoTalkPhoneBasic"		// configuration of Video Talk Phone Basic ( corresponding to CFG_VIDEO_TALK_PHONE_BASIC_INFO )
#define CFG_CMD_APP_EVENT_LANGUAGE				"AppEventLanguage"			// configuration of App Event Language ( corresponding to CFG_APP_EVENT_LANGUAGE_INFO )
#define CFG_CMD_LOGIN_FAILURE_ALARM				"LoginFailureAlarm"			// configuration of login failure alarm(Corresponding to CFG_LOGIN_FAILURE_ALARM)
#define CFG_CMD_DROPBOXTOKEN                    "DropBoxToken"              // configuration of Dropbox Token( corresponding to CFG_DROPBOXTOKEN_INFO)
#define CFG_CMD_IDLINGTIME						"IdlingTime"				// configuration of Idling time(corresponding to CFG_IDLINGTIME_INFO)
#define CFG_CMD_CARDIVERSTATE					"CarDiverState"				// configuration of driver state(corresponding to CFG_CARDIVERSTATE_INFO)
#define CFG_CMD_VEHICLE							"Vehicle"					// configuration of vehicle(corresponding to CFG_VEHICLE_INFO)
#define CFG_CMD_PTZDEVICE                       "PtzDevice"                 // configuration of Ptz Device( corresponding to CFG_PTZDEVICE_INFO)
#define CFG_CMD_DEVLOCATION                     "DevLocation"               // configuration of Device Location( corresponding to CFG_DEVLOCATION_INFO)
#define CFG_CMD_SMARTHOME_SCENELIST				"SmartHomeSceneList"		// configuration of scene list corresponding to CFG_SMARTHOME_SCENELIST_INFO)
#define CFG_CMD_LIGHTING_V2						"Lighting_V2"				// configuration of camera sensitivity(corresponding to CFG_LIGHTING_V2_INFO)
#define CFG_CMD_KBUSER_PASSWORD					"KbuserPassword"            // configuration of keyboard operation user(corresponding to CFG_KBUSER_USERS_INFO)
#define	CFG_CMD_ACCESS_OEM						"AccessOEMSettings"			// configuration of access OEM(corresponding to CFG_ACCESS_OEM_INFO)
#define CFG_CMD_FIRE_WARNING_EXT				"FireWarningExt"			// configuration of fire warning extend��corresponding to CFG_FIREWARNING_EXT_INFO��
#define CFG_CMD_LOCATION_CALIBRATE				"LocationCalibrate"			// configuration of location calibrate(corresponding to CFG_LOCATION_CALIBRATE_INFO)
#define	CFG_CMD_THERM_DENOISE					"ThermDenoise"				// configuration of thermal specific movement denoise(corresponding to CFG_THERM_DENOISE)
#define	CFG_CMD_CONSTANT_LAMP					"ConstantLamp"				//configuration of intelligent traffic lamp config(corresponding to CFG_CONSTANT_LAMP_INFO)
#define	CFG_CMD_TRAFFIC_IO					    "TrafficIO"				    //configuration of traffic coil config, corresponding to CFG_TRAFFIC_IO
#define	CFG_CMD_MONITOR_WALL_COLLECTION_MAP		"MonitorWallCollectionMap"  // Pre-connected configuration of TV Wall,corresponding to CFG_MONITOR_WALL_COLLECTION_MAP_INFO,Channel only supports - 1
#define	CFG_CMD_VIDEO_INPUT_GROUP		        "VideoInputGroup"           // Video input group configuration,corresponding to CFG_VIDEO_INPUT_GROUP_INFO 
#define	CFG_CMD_DOOR_NOT_CLOSE					"DoorNotClosed"				// door not close configuration, corresponding to CFG_DOOR_NOT_CLOSE_INFO
#define	CFG_CMD_BREAK_IN						"BreakIn"					// break in configuration, corresponding to CFG_BREAK_IN_INFO
#define	CFG_CMD_ANTI_PASSBACK					"AntiPassback"				// antiPassback configuration, corresponding to CFG_ANTI_PASSBACK_INFO
#define	CFG_CMD_DURESS							"Duress"					// duress configuration,corresponding to CFG_DURESS_INFO
#define	CFG_CMD_MALICIOUS_ACCESSCONTROL			"MaliciousAccessControl"	// maliciousAccessControl configuration,corresponding to CFG_DOOR_MALICIOUS_ACCESSCONTROL_INFO
#define CFG_CMD_REGULATOR_DETECT				"RegulatorDetect"			// regulator detect configuration, corresponding to  CFG_REGULATOR_DETECT_INFO. valid for thermal channel

#define CFG_CMD_REMOTE_ANALYSEGLOBAL                   "RemoteVideoAnalyseGlobal"        // Remote video analyze global config(corresponding struct CFG_ANALYSEGLOBAL_INFO)
#define CFG_CMD_REMOTE_ANALYSEMODULE                   "RemoteVideoAnalyseModule"        // Remote video analyze module config(corresponding struct CFG_ANALYSEMODULES_INFO)
#define CFG_CMD_REMOTE_ANALYSERULE                     "RemoteVideoAnalyseRule"          // Remote video analyze rule config(corresponding struct CFG_ANALYSERULES_INFO)

#define CFG_CMD_INFRARED_CONFIG                        "InfraredSet"                     // Infrared function configuration (corresponding to CFG_INFRARED_INFO)
#define CFG_CMD_ACCESS_DOOR_STATUS				"AccessDoorStatus"			// The customized timetable corresponds to the door status configuration and the access control card time period (CFG_ACCESS_TIMESCHEDULE_INFO) is used in conjunction with the corresponding (CFG_ACCESS_DOORSTATUS_INFO)

#endif // CONFIG_COMMANDS_H
